### ISSUE TITLE
Migration to 12.0

### ISSUE THREAD

**Issue by alexey-pelykh** [camptocamp/connector-jira#7]
Any plans on this?

**Comment by guewen** [comment]
Nothing planned yet on our side.

**Comment by alexey-pelykh** [comment]
Gotcha! For migration thing, policy is same/similar to OCA?

**Comment by guewen** [comment]
About what? We follow the same code guidelines than the OCA. Regarding the migration, we don't use the "filter-branch" way, we start from the branch from the previous version. Let me know if you need a 12.0 branch (but as we are working on the 11.0 now, changes will have to be forward-ported).

**Comment by alexey-pelykh** [comment]
Closing in favor of https://github.com/OCA/connector-jira/pull/4
